name: civic_lens
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  url_launcher: ^6.2.0
  flutter_launcher_icons: ^0.14.4
  geocoding: ^4.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.0
  animate_do: ^4.2.0

  # Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2

  # AI & Camera
  image_picker: ^1.0.4
  google_generative_ai: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon" # The name of the icon file on Android
  ios: true # Generate for iOS
  image_path: "assets/icon/icon.png" # ðŸ‘ˆ PATH TO MASTER IMAGE
  min_sdk_android: 21 # Helps with newer Android icon styles
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code" 